version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  stream:
    class: logging.StreamHandler
    formatter: simple
loggers:
  root_log:
    level: INFO
    handlers: [stream]
