Services:
  - name: Google
    URL: https://maps.googleapis.com/maps/api/geocode/json?
    address_field: address
    request_param:
      key: AIzaSyDUNF1zBmo9VBNlNxsiXp5ux-0BUJMTmnc
    response_paths:
      lat: results.list__0.geometry.location.lat
      lng: results.list__0.geometry.location.lng
  - name: HERE
    URL: https://geocoder.api.here.com/6.2/geocode.json?
    address_field: searchtext
    request_param:
      app_code: 6iRP835fSnTWSbiCDqtgBA
      app_id: H3XSJUNFYE6gJyETcM8x
    response_paths:
      lat: Response.View.list__0.Result.list__0.Location.DisplayPosition.Latitude
      lng: Response.View.list__0.Result.list__0.Location.DisplayPosition.Longitude

